import "server-only";
import PDFDocument from "pdfkit";
import { db } from "./db";
import { randomToken } from "./crypto";
import { meter } from "./usage";

// ─────────────────────────────────────────────────────────────────────────────
// Document generation + secure temporary delivery. For the MVP a document is a
// self-contained HTML page stored inline and reachable via an unguessable token
// URL that expires. In production this renders to PDF and stores in object
// storage with signed, expiring URLs. Branding is pulled from the tenant.
// ─────────────────────────────────────────────────────────────────────────────

const DOC_TTL_MS = 30 * 60 * 1000; // 30 minutes

type Branding = { assistantName?: string; primaryColor?: string; pdfFooter?: string };

export type GeneratedDoc = { url: string; filename: string; token: string };

/** Render a pdfkit document to a Buffer. */
function renderPdf(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    build(doc);
    doc.end();
  });
}

/** Store bytes as an expiring, token-addressed Document. The URL is absolute
 *  (PUBLIC_BASE_URL) so WhatsApp can fetch it; falls back to relative for local. */
async function store(opts: {
  tenantId: string; contactId?: string; kind: string; filename: string; base64: string;
}): Promise<GeneratedDoc> {
  const token = randomToken();
  await db.document.create({
    data: {
      tenantId: opts.tenantId, contactId: opts.contactId ?? null, kind: opts.kind,
      filename: opts.filename, content: opts.base64, token,
      expiresAt: new Date(Date.now() + DOC_TTL_MS),
    },
  });
  await meter(opts.tenantId, "document");
  const base = (process.env.PUBLIC_BASE_URL || "").replace(/\/$/, "");
  return { url: `${base}/d/${token}`, filename: opts.filename, token };
}

// Shared PDF chrome: branded header band + footer.
function pdfHeader(doc: PDFKit.PDFDocument, org: string, title: string, color: string) {
  doc.rect(0, 0, doc.page.width, 90).fill(color);
  doc.fill("#ffffff").fontSize(20).font("Helvetica-Bold").text(org, 50, 30);
  doc.fontSize(12).font("Helvetica").text(title, 50, 58);
  doc.fill("#0f172a").moveDown(3);
  doc.y = 120;
}
function pdfFooter(doc: PDFKit.PDFDocument, note: string) {
  doc.fontSize(9).fill("#94a3b8").font("Helvetica")
    .text(note, 50, doc.page.height - 70, { width: doc.page.width - 100, align: "center" });
}
function row(doc: PDFKit.PDFDocument, label: string, value: string, bold = false) {
  const y = doc.y;
  doc.fontSize(12).fill("#475569").font("Helvetica").text(label, 50, y);
  doc.fill("#0f172a").font(bold ? "Helvetica-Bold" : "Helvetica").text(value, 300, y, { width: 245, align: "right" });
  doc.moveDown(0.8);
}

/** Payslip PDF with the full deductions breakdown. */
export async function generatePayslipPdf(opts: {
  tenantId: string; contactId?: string; org: string; color?: string; footer?: string;
  name: string; title?: string; period: string; currency: string; gross: number; deductions: number; net: number;
}): Promise<GeneratedDoc> {
  const color = opts.color ?? "#4f46e5";
  const money = (n: number) => `${opts.currency} ${n.toLocaleString("en-US")}`;
  const pdf = await renderPdf((doc) => {
    pdfHeader(doc, opts.org, "Payslip", color);
    doc.fontSize(14).font("Helvetica-Bold").fill("#0f172a").text(opts.name);
    doc.fontSize(11).font("Helvetica").fill("#475569").text(`${opts.title ?? "Employee"} · Pay period ${opts.period}`);
    doc.moveDown(1.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(1);
    row(doc, "Gross pay", money(opts.gross));
    row(doc, "Total deductions", `- ${money(opts.deductions)}`);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(1);
    row(doc, "Net pay", money(opts.net), true);
    pdfFooter(doc, opts.footer ?? `${opts.org} · Confidential payslip · Generated by P2Less`);
  });
  return store({ tenantId: opts.tenantId, contactId: opts.contactId, kind: "payslip", filename: `payslip-${opts.period}.pdf`, base64: pdf.toString("base64") });
}

/** Fee statement PDF — billed / paid / balance for a student. */
export async function generateFeeStatementPdf(opts: {
  tenantId: string; contactId?: string; org: string; color?: string; footer?: string;
  studentName: string; grade?: string; currency: string; billed: number; paid: number; balance: number; dueDate: string;
}): Promise<GeneratedDoc> {
  const color = opts.color ?? "#0f766e";
  const money = (n: number) => `${opts.currency} ${n.toLocaleString("en-US")}`;
  const pdf = await renderPdf((doc) => {
    pdfHeader(doc, opts.org, "Fee Statement", color);
    doc.fontSize(14).font("Helvetica-Bold").fill("#0f172a").text(opts.studentName);
    doc.fontSize(11).font("Helvetica").fill("#475569").text(`${opts.grade ?? "Student"} · Statement date ${new Date().toISOString().slice(0, 10)}`);
    doc.moveDown(1.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(1);
    row(doc, "Total billed", money(opts.billed));
    row(doc, "Paid to date", `- ${money(opts.paid)}`);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(1);
    row(doc, "Balance due", money(opts.balance), true);
    row(doc, "Due date", opts.dueDate);
    pdfFooter(doc, opts.footer ?? `${opts.org} · Official fee statement · Generated by P2Less`);
  });
  return store({ tenantId: opts.tenantId, contactId: opts.contactId, kind: "fee_statement", filename: `fee-statement-${slug(opts.studentName)}.pdf`, base64: pdf.toString("base64") });
}

/** Leave-request confirmation PDF. */
export async function generateLeavePdf(opts: {
  tenantId: string; contactId?: string; org: string; color?: string; footer?: string;
  name: string; reference: string; startDate: string; endDate: string; reason?: string; status: string;
}): Promise<GeneratedDoc> {
  const color = opts.color ?? "#4f46e5";
  const pdf = await renderPdf((doc) => {
    pdfHeader(doc, opts.org, "Leave Request", color);
    doc.fontSize(14).font("Helvetica-Bold").fill("#0f172a").text(opts.name);
    doc.fontSize(11).font("Helvetica").fill("#475569").text(`Reference ${opts.reference}`);
    doc.moveDown(1.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(1);
    row(doc, "From", opts.startDate);
    row(doc, "To", opts.endDate);
    if (opts.reason) row(doc, "Reason", opts.reason);
    row(doc, "Status", opts.status.toUpperCase(), true);
    pdfFooter(doc, opts.footer ?? `${opts.org} · Leave request receipt · Generated by P2Less`);
  });
  return store({ tenantId: opts.tenantId, contactId: opts.contactId, kind: "leave", filename: `leave-${opts.reference}.pdf`, base64: pdf.toString("base64") });
}

export async function generateReportCard(opts: {
  tenantId: string;
  contactId: string;
  studentName: string;
  grade: string;
  results: { subject: string; score: number; grade: string }[];
  branding?: Branding;
}): Promise<{ url: string; filename: string; token: string }> {
  const color = opts.branding?.primaryColor ?? "#0f766e";
  const footer = opts.branding?.pdfFooter ?? "Generated by P2Less";
  const rows = opts.results
    .map(
      (r) =>
        `<tr><td>${escapeHtml(r.subject)}</td><td style="text-align:right">${r.score}</td><td style="text-align:center">${escapeHtml(r.grade)}</td></tr>`,
    )
    .join("");
  const avg = opts.results.length
    ? Math.round(opts.results.reduce((s, r) => s + r.score, 0) / opts.results.length)
    : 0;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Report Card — ${escapeHtml(opts.studentName)}</title>
<style>
  body{font-family:system-ui,Segoe UI,Arial,sans-serif;margin:0;color:#0f172a;background:#f8fafc}
  .sheet{max-width:640px;margin:24px auto;background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden}
  .hd{background:${color};color:#fff;padding:20px 24px}
  .hd h1{margin:0;font-size:20px}.hd p{margin:4px 0 0;opacity:.85;font-size:13px}
  .bd{padding:24px}
  table{width:100%;border-collapse:collapse;font-size:14px}
  th,td{padding:10px;border-bottom:1px solid #e2e8f0}
  th{text-align:left;color:#64748b;font-weight:600}
  .avg{margin-top:16px;font-size:15px;font-weight:600}
  .ft{padding:14px 24px;color:#94a3b8;font-size:12px;border-top:1px solid #e2e8f0}
</style></head><body>
<div class="sheet">
  <div class="hd"><h1>Report Card</h1><p>${escapeHtml(opts.studentName)} · ${escapeHtml(opts.grade)}</p></div>
  <div class="bd">
    <table><thead><tr><th>Subject</th><th style="text-align:right">Score</th><th style="text-align:center">Grade</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <div class="avg">Overall average: ${avg}%</div>
  </div>
  <div class="ft">${escapeHtml(footer)} · This link is confidential and expires in 30 minutes.</div>
</div></body></html>`;

  const token = randomToken();
  const filename = `report-card-${slug(opts.studentName)}.html`;
  await db.document.create({
    data: {
      tenantId: opts.tenantId,
      contactId: opts.contactId,
      kind: "report_card",
      filename,
      content: html,
      token,
      expiresAt: new Date(Date.now() + DOC_TTL_MS),
    },
  });
  await meter(opts.tenantId, "document");
  return { url: `/d/${token}`, filename, token };
}

export async function getDocumentByToken(token: string) {
  const doc = await db.document.findUnique({ where: { token } });
  if (!doc) return null;
  if (doc.expiresAt < new Date()) return { expired: true as const };
  return { expired: false as const, doc };
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}
function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
